### PR TITLE
Allow to set more options

### PR DESCRIPTION
**Pull request by h3ndrk**
Thanks for the great bindings library!

For my project, I need more control over the options of the phoneme generation. Therefore this PR adds more options to the `PhonemeGenOptions::Standard` enum variant.

This repository seems to not be formatted according to standard `rustfmt` which might introduce some unchanged lines that were not intended. Please consider to reformat this repository to make contributing easier. I did not format the `lib.rs` to reduce the  number of change lines in this PR. :smiley:

Feel free to discuss or propose alternatives for setting the options more easily from the outside. Thanks in advance!

### CODE REVIEW

**Comment by GnomedDev** [comment]
Right then, I've formatted the repo using rustfmt and updated some dependencies, can you rebase?

**Comment by h3ndrk** [comment]
Thanks for formatting! :tada:

The files in `tests/` also needed formatting. I did that in another commit, but I can drop it if you want. :smiley:

Should be rebased.

**Comment by GnomedDev** [comment]
Thanks, although I have concerns that most of these text modes are going to be unusable due to the fact that `&str` is always UTF8 encoded?

**Comment by h3ndrk** [comment]
That might be true. I only added all available variants without testing.

I also thought whether we want to exclude `Mbrola` because there is a dedicated enum variant in `PhonemeGenOptions`. :thinking:

Do you want to be close to upstream or only expose what is implemented and provide a single way to do things?

**Comment by GnomedDev** [comment]
I want to smooth over the weirdness in the C api, so I'd prefer to only expose what works.

**Comment by h3ndrk** [comment]
Fine for me. Better now? Only UTF-8 is supported in the `TextMode` because the others might use ISO-8859 or some wide character formats.

**Comment by GnomedDev** [comment]
Looks good to me!

**Pull request merged**
